version: "2"
services:
  java:
    image: openjdk:17
    volumes:
      - ./:/app
    command: bash -c "cd /app && java -jar partner-service-1.0.1-all.jar --port=8032"
    ports:
      - 8032:8032
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  candle_kafka:
    image: wurstmeister/kafka
    container_name: "candle_kafka"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181